### ISSUE TITLE
No sound when notofication appears.

### ISSUE THREAD

**Issue by ghost** [raelgc/scudcloud#414] opened 2016-03-10 16:03 UTC
Hello,

I'm working on Ubuntu 15.10 with unity 7.3.3. When notification is shown, I didn't get any sound. Also in settings, where there is a place to change the sound(shown on screen) and I will click on blue sign(in 'Sound' part) connected with sound, nothing happens, but should to.
![slack_sound](https://cloud.githubusercontent.com/assets/12530184/13675410/babb7ece-e6e1-11e5-86f5-74efb6619cf6.png)

Btw. thank you for your work ;)

**Comment by raelgc** [comment] 2016-03-10 16:18
Hi @kkochanski-neurosys and thanks for reporting this issue.

But this is a duplicate of #120 (it was closed and I've reopened it). Unfortunately, no solution until now.

**Closed as completed by raelgc** 2016-03-10 16:18 UTC
