### ISSUE TITLE
#general channel is missing from sidebar

### ISSUE THREAD

**Issue by KlipperKyle** [raelgc/scudcloud#462] opened 2016-06-25 01:25 UTC
## ScudCloud Version

Paste the output for `scudcloud --version` below:

```
/usr/lib/python3.5/site-packages/scudcloud/notifier.py:3: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Notify
ScudCloud 1.25
Python 3.5.1
Qt 4.8.7
PyQt 4.11.4
SIP 4.18
```
## Distro and Desktop info
- Distribution: Arch Linux `x86_64`
- Version/Release: [scudcloud-1.25-1](https://aur.archlinux.org/packages/scudcloud)
- Desktop environment: Window Maker with some MATE backend
## Expected behavior

Each slack account has a #general room displayed in the sidebar.
## Actual behavior

There is no #general room listed in the sidebar.  This problem occurs on all 3
Slack accounts that I use.

This was working a couple of days ago (21 June), so I think something changed
server-side that broke this.  (I have neither rebuilt nor updated scudcloud
since 18 June.)

It is still possible to switch to the #general by running `/open #general` or
clicking on a link that points to #general.
## Steps to reproduce
1. Launch scudcloud
2. Login to Slack
3. Observe.  There is no #general room listed in the sidebar.

![scud](https://cloud.githubusercontent.com/assets/6385218/16353933/9aa2bb16-3a38-11e6-8798-020946492e96.png)

**Comment by keevitaja** [comment] 2016-06-25 08:18
I confirm the issue. It is happening to all my channels. The default channel, no matter how it is named, does not show on the sidebar. 

Using Arch Linux and ScudCloud 1.25

![slack-sc](https://cloud.githubusercontent.com/assets/158787/16355667/964ffafe-3ac6-11e6-84ca-c56c83dd0803.png)

This is how it looks from the borwser:

![slack-web](https://cloud.githubusercontent.com/assets/158787/16355668/98572b9c-3ac6-11e6-8547-2008471606ab.png)

**Comment by raelgc** [comment] 2016-06-25 16:49
Duplicate of #454. If this is happening, right click and select `Reload`.

**Closed as completed by raelgc** 2016-06-25 16:49 UTC

**Comment by doublebyte1** [comment] 2016-06-27 14:11
The same problem is reproduced on my computer, using Ubuntu Xenial:

ScudCloud 1.24
Python 3.5.1+
Qt 4.8.7
PyQt 4.11.4
SIP 4.17

If I browse the channels, the #general is not there, despite I can open it with `/open #general`.
I am able to see it on the side-bar, by using @raelgc suggestion of reloading the channels.

![scudcloud](https://cloud.githubusercontent.com/assets/1038897/16382602/c6ff7ffa-3c81-11e6-8674-d0061fd57d0b.png)
