### ISSUE TITLE
General channel disapear from the list of channels, I cannot sign in to another team

### ISSUE THREAD

**Issue by HERRKIN** [raelgc/scudcloud#472] opened 2016-07-04 14:03 UTC
## ScudCloud Version

Paste the output for `scudcloud --version` below:
``
ScudCloud 1.22
Python 3.5.1+
Qt 4.8.7
PyQt 4.11.4
SIP 4.17
## Distro and Desktop info
- Distribution: ubuntu 
- Version/Release: 16.04
- Desktop environment: default (unity)
## Expected behavior

when I sign in the app starts in the general channel, if I saw another channel I can just go back to general by hitting its name on the list of channel on the left. 

if I hit menu, sign in to another team it should open a window to let me sign in to another team
## Actual behavior

the app starts in the general channel but if I enter another channel I can't go back to general becuse it is not on the list of channels. 

it does nothing when I hit sign in to another team
## Steps to reproduce
1. I trully don't know how you can reproduce it, I found that some times the general channel works as expected but I have never been able to sign in to another channel from this app.

**Comment by raelgc** [comment] 2016-07-04 14:06
Duplicate of #454. Please, upgrade to 1.29.

**Closed as completed by raelgc** 2016-07-04 14:06 UTC

**Comment by HERRKIN** [comment] 2016-07-04 14:45
but I do `sudo apt-get upgrade scudcloud` the system says it is in the latest version, why can't I upgrade it that way?

**Comment by HERRKIN** [comment] 2016-07-04 15:00
ok I could upgrade to 1.29 and the general channel problem seems to have been solved but I still see no functionality when I hit the sign in to another team menu

**Comment by raelgc** [comment] 2016-07-04 15:37
Thank you for the feedback @HERRKIN.

Can you tell me which option to signin to another team is not working? Actually we have:
1. `File` > `Sign in to Another Team`
2. `Team menu` > `Sign in to another team ...`

**Comment by HERRKIN** [comment] 2016-07-04 15:45
I just tried both ways the functionality is broken here

**Comment by HERRKIN** [comment] 2016-07-06 15:02
I have 
ScudCloud 1.30
Python 3.5.1+
Qt 4.8.7
PyQt 4.11.4
SIP 4.17
Still cannot sign in to another team
