### ISSUE TITLE
Change *.desktop file to work with custom icon themes

### ISSUE THREAD

**Issue by keeferrourke** [raelgc/scudcloud#564] opened 2017-04-12 04:22 UTC
## ScudCloud Version

Paste the output for `scudcloud --version` below:
```
ScudCloud 1.55
Python 3.5.2+
Qt 5.6.1
PyQt 5.7
SIP 4.18.1
```

## Distro and Desktop info

  - Distribution: Xubuntu
  - Version/Release: 16.10
  - Desktop environment: XFCE (with GNOME libs)

## Expected behavior
With a custom icon theme applied, it is expected that the scudcloud icon change with the rest of the theme. This does not and cannot happen because of the hardcoded Icon path in the desktop file.

## Actual behavior
The scudcloud icon does not change with the rest of the icon theme.

## Steps to reproduce
 1. Install scudcloud
 2. Notice the custom icon theme is not honoured

## How to fix:
In the application desktop file located at `/usr/share/applications/scudcloud.desktop`, change line 11 from:
```
Icon=/usr/share/pixmaps/scudcould.png
```
to:
```
Icon=scudcloud
```
The operating system will locate the appropriate icon from the current theme, and failing to find it, it will fall back on the scudcloud pixmap. This fix will also remove the need for the instructions in the README for how to change the icon.

**Comment by raelgc** [comment] 2017-04-12 13:54
Hi @keeferrourke and thanks for raising this issue.

Indeed, if I remove the path to the icon, Unity will start to use the systray icons, which are mono-colored ones. But I don't want the systray icons used in the `.desktop` file.

If you can suggest a way to make Unity use another icon than the systray ones, I'll remove the path.

**Comment by keeferrourke** [comment] 2017-04-12 15:55
Well the freedesktop specification tells desktop environments to look for application icons in /usr/share/icons, so I would suggest that you install all icons to `/usr/share/icons/hicolor` -- this is where most application icons are supposed to go -- and then do one of two things:

a) change the name of the systray icons to something like `scudcloud-tray` or `scudcloud-indicator`, and update the names throughout the source to reflect this change, or
b) tell the desktop file to look for another icon such as `scudcloud-icon` or `scudcloud-desktop`; this is probably not as good practise, but is the solution with the least amount of work required.

**Comment by raelgc** [comment] 2017-04-12 16:52
Nice suggestions! I'll test them! Thank you!

**Comment by raelgc** [comment] 2017-04-12 20:19
This is a duplicate of #456

**Closed as completed by raelgc** 2017-04-12 20:19 UTC

**Comment by keeferrourke** [comment] 2017-04-13 01:37
Didn't see that issue, thanks for bringing it to my attention. Issue 456 hasn't been active in nearly a year though, is this still going to be addressed?

**Comment by raelgc** [comment] 2017-04-13 10:29
Yeap, I'll work on it, as now most issues from the transition from Qt4 -> Qt5 are being addressed.
