### ISSUE TITLE
Channels frequently missing that should exist.

### ISSUE THREAD

**Issue by ken-roberts** [raelgc/scudcloud#480] opened 2016-07-22 17:24 UTC
## ScudCloud Version 1.10-1 on Ubuntu 15.10

Paste the output for `scudcloud --version` below:
``
ScudCloud 1.10
Python 3.4.3+
Qt 4.8.6
PyQt 4.11.4
SIP 4.16.9
## Distro and Desktop info
- Distribution: Ubuntu
- Version/Release: 15.10
- Desktop environment: Default
## Expected behavior

The existing channels all show up in the main screen.
## Actual behavior

At least one channel fails to appear. The most frequently missing channel is the #general talk-to-everyone channel. Sometimes as many as 3 channels are gone.

If the app starts while showing #general I can chat on it, but once I click away I can't connect to #general anymore.
## Steps to reproduce
1. Start the app.

There are 13 channels actually on Slack that show up for everyone else.

Rarely all the channels show up.  Also rarely less than 12 channels show up.

**Comment by raelgc** [comment] 2016-07-23 22:56
Please, upgrade. ScudCloud is now in version 1.30. This is duplicate of #454, which is fixed.

**Closed as completed by raelgc** 2016-07-23 22:56 UTC
