### ISSUE TITLE
Unable to edit messages

### ISSUE THREAD

**Issue by carymrobbins** [raelgc/scudcloud#465] opened 2016-06-28 16:38 UTC
_I'd be happy to fix this myself if someone could point me in the right direction!_
#### NOTE: I'm actually building from source at HEAD of master.

```
% scudcloud --version
ScudCloud 1.25
Python 3.4.3
Qt 4.8.6
PyQt 4.10.4
SIP 4.15.5
```
## Distro and Desktop info
- Distribution: Ubuntu
- Version/Release: 14.04
- Desktop environment: Xmonad
## Expected behavior

The `...` > `Edit Message` button should allow me to edit my posted messages.

Pressing `up` on my keyboard should allow me to edit my last posted message.
## Actual behavior

Using the `Edit Message` button doesn't actually let you edit the message, the dialog disappears upon clicking anything.

Using the `up` button to edit the last message doesn't allow you to click `Save` or even `Cancel`. The only way to then use the client is to right-click and reload the page.
## Steps to reproduce
1. Click `...` then `Edit Message`
2. Try to edit the message
3. Can't

---
1. Press `up` on the keyboard's arrow keys
2. Edit the message
3. Try to save the edited message
4. Can't

**Comment by igorp1024** [comment] 2016-06-28 20:55
Same on Ubuntu 16.04 (Xenial Xerus).

**Comment by rsyring** [comment] 2016-06-28 22:02
ditto

**Comment by loonies** [comment] 2016-06-29 07:09
This is duplicate of #459

**Closed as completed** 2016-07-01 14:07 UTC
