### ISSUE TITLE
Preferences not working

### ISSUE THREAD

**Issue by mcharron** [raelgc/scudcloud#177] opened 2015-07-08 12:28 UTC
Hi,

On Ubuntu 12.04LTS, when I open preferences, each fields are in readonly... Or it seems to. They appear in gray.

There's no way to get it to work, notifications doesn't show on my desktop, I don't know if I'm doing something wrong or not...

Thanks

**Comment by metadan** [comment] 2015-07-14 11:17
I also have an issue with preferences on 14.04. Nothing happens when I click it.

**Comment by lots0logs** [comment] 2015-07-14 15:09
+1 I can confirm this starting happening when I updated to v1.0.50 - 89c0291 I'm going to try the previous version now (I was a few versions behind when I updated to 1.0.50)

**Update:** The bug seems to have been introduced sometime after v1.0.48 and before v1.0.49. So to be clear, v1.0.48 does not have the issue. I hope that helps :smile:

**Comment by lots0logs** [comment] 2015-07-19 14:26
It turns out I was wrong. The issue occurs on all of the last few versions it seems. I discovered that deleting the following file resolves the issue (until the next time you start the app):

```
~/.cache/ScudCloud Slack_SSB/PluginMetadataCache.bin
```

**Comment by raelgc** [comment] 2015-07-26 03:10
New version released with contributed fixes. Please, re-test.

**Comment by mcharron** [comment] 2015-07-30 15:28
@raelgc Sorry, I updated to 15.04 since I posted the issue, I'm not able to retest it. If somebody can test...

**Comment by lots0logs** [comment] 2015-07-30 21:42
@raelgc The issue still occurs, though not as often. It seems almost random. When it does occur, simply exiting the app and restarting it usually resolves it (though sometimes requires multiple restarts).

**Comment by raelgc** [comment] 2015-08-06 14:25
Just to be clear: `Preferences` will appear only when the Slack connection was made. If, for some reason, it got `offline`, then it'll be grayed.

**Closed as completed by raelgc** 2015-08-06 14:25 UTC
