### ISSUE TITLE
Multiple teams: only first team "logs in" 

### ISSUE THREAD

**Issue by Gibol** [raelgc/scudcloud#81] opened 2015-04-24 11:56 UTC
When starting ScudCloud only first team is loading. You have to click on the other teams button on the left panel to load them, otherwise you cant recieve their the messages. In my opinion, every team should load at startup.

**Comment by Slater91** [comment] 2015-04-25 13:11
On top of that, I found out that only the second team (the one which does not automatically log in) gets the icon displayed, while the first one doesn't.

**Comment by raelgc** [comment] 2015-04-25 13:23
@jshawl Can you take a look the icon not being displayed for first team?

**Comment by jshawl** [comment] 2015-04-25 16:34
This appears to be an issue with Slack: https://github.com/raelgc/scudcloud/blob/810e97983bafea1e16f62b3caafb1722dc4927c3/scudcloud-1.0/resources/scudcloud.js#L35

You can reproduce this by opening a console while logged into *.slack.com and typing

``` js
TS.getAllTeams()
```

The first object is always missing the image.

**Comment by nazar-pc** [comment] 2015-05-30 18:20
Well, since minimized start is implemented, would be nice to fix this one.
There is no problems with "remember me" feature now, just need to click to load team.
What exactly happens when team icon on the left is clicked? Is there any way to trigger it automatically?

**Comment by raelgc** [comment] 2015-05-30 19:16
@nazar-pc When the first team is loaded, we call `TS.getAllTeams()` (which returns teams id and name), then ScudCloud populates the left pane with them.

When you click in the team icon (for the first time), then ScudCloud creates a new QWebView (the HTML container) for the team.

This is the same behavior from the Mac version (at least the last time I checked in a Hackintosh VM).

As QWebView is a heavy QT widget, probably the reason to load only on the first demand is to avoid overload the computer when Slack is started.

But we can create a simple test between us. Give me more some days and I'll post here a test version.

**Comment by nazar-pc** [comment] 2015-05-30 20:36
@raelgc, that would be nice, can't wait to test it.

**Comment by raelgc** [comment] 2015-06-16 12:55
@nazar-pc, please test this.

Open, as `root` or `sudo` file `/opt/scudcloud/lib/scudcloud.py`. 

Then in the line `187`, you'll find this method:

``` python
    def teams(self, teams):
        if teams is not None and len(teams) > 1:
            self.leftPane.show()
            for t in teams:
                try:
                    self.leftPane.addTeam(t['id'], t['team_name'], t['team_url'], t['team_icon']['image_88'], t == teams[0])
                except:
                    self.leftPane.addTeam(t['id'], t['team_name'], t['team_url'], '', t == teams[0])
```

Please, add the last line like displayed below, paying attention to preserve white spaces in the beginning of the line:

``` python
    def teams(self, teams):
        if teams is not None and len(teams) > 1:
            self.leftPane.show()
            for t in teams:
                try:
                    self.leftPane.addTeam(t['id'], t['team_name'], t['team_url'], t['team_icon']['image_88'], t == teams[0])
                except:
                    self.leftPane.addTeam(t['id'], t['team_name'], t['team_url'], '', t == teams[0])
                self.switchTo(t['team_url'])
```

Save the file and restart ScudCloud. Let me know if it works as expected.

**Comment by nazar-pc** [comment] 2015-06-16 16:32
Added that line, nothing changed. No error messages when running from terminal.

**Comment by raelgc** [comment] 2015-06-16 17:21
@nazar-pc Our teams do not get logged in automatically?

**Comment by nazar-pc** [comment] 2015-06-16 17:36
Yes, as it was before change

**Comment by raelgc** [comment] 2015-06-16 19:13
@nazar-pc I've tested this change here, and team get logged automatically. The only weird stuff, and not sure if it's related, is I can see some random team switches happening in a random way. Anyway, I'll test more before publish this.

**Comment by nazar-pc** [comment] 2015-06-16 19:16
Sorry, I've put it into `except` part.
Logging in automatically seems to work fine, I'll test this more as well.

**Comment by nazar-pc** [comment] 2015-06-17 04:58
There is one bug.
I have 2 teams, both are logged in at start, this is fine.
First one is active by default, this is fine too.
Now about weird stuff:
- click on any channel - it switches to second team
- switch to second team, click any channel - it switches to first team

Basically choosing any channel in any team switches me to opposite team immediately (while selecting proper channel in target team, so that I can go back and chat finally).
Not sure how it behaves with teams number more than 2.

**Comment by raelgc** [comment] 2015-06-17 12:10
@nazar-pc, yeap, I saw the same behaviour here. Revert locally, please, I'll dig a bit to see why this is happening.

Thank you for helping me to test that!

**Comment by raelgc** [comment] 2015-06-17 12:10
Anyway, the first team icon is fixed :)

**Comment by Slater91** [comment] 2015-06-18 12:43
Hi @raelgc, it seems like the last updates breaks everything. Not only teams after the first do not automatically get logged, but desktop notifications appear as disabled and I can't either select preferences nor log in to another team.
Starting ScudCloud from the terminal does not display any apparent issue, even in debug mode.

**Comment by raelgc** [comment] 2015-06-18 13:11
@Slater91 I just pushed a new version, can you update/upgrade again, please?

**Comment by Slater91** [comment] 2015-06-18 13:29
@raelgc: the latest update fixes all the issues and now everything is working again! The second team does in fact get logged in, by the way!

Thank you!

**Closed as completed** 2015-06-18 13:56 UTC
