### ISSUE TITLE
#general has disappeared from channel list on Ubuntu 16.04

### ISSUE THREAD

**Issue by shevek** [raelgc/scudcloud#461] opened 2016-06-25 01:10 UTC
## ScudCloud Version

Paste the output for `scudcloud --version` below:

```
/usr/lib/python3/dist-packages/scudcloud/notifier.py:3: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Notify
/usr/lib/python3/dist-packages/scudcloud/scudcloud.py:27: PyGIWarning: Unity was imported without specifying a version first. Use gi.require_version('Unity', '7.0') before import to ensure that the right version gets loaded.
  from gi.repository import Unity, Dbusmenu
ScudCloud 1.26
Python 3.5.1+
Qt 4.8.7
PyQt 4.11.4
SIP 4.17

```
## Distro and Desktop info
- Distribution:Ubuntu
- Version/Release:16.04
- Desktop environment:xfce
## Expected behavior

Log in.
See #general listed.
See 3 channels listed.
## Actual behavior

Log in.
See only #house and #random.
- I can /join #general, and its content appears in the main window, but it never appears in the channel list.
- Channel list says "all 2 channels" although there are really 3.
- If I go to Slack on the web, #general is listed. This is true for all 5 slacks I am in.
- I appear to get notifications for #general even though I can't see it.
- I'm the Slack admin, so this isn't a permissions issue.
- It's fine on the web.

Did not affect 15.10 or Slack pre-today or something. I'm not sure if it's my US upgrade or their API change.
## Steps to reproduce
1. Launch scudcloud
2. Look for #general.
3. It's not there.

I can invite you to our Slack if that helps you to diagnose.

**Comment by raelgc** [comment] 2016-06-25 16:49
Duplicate of #454. If this is happening, right click and select `Reload`.

**Closed as completed by raelgc** 2016-06-25 16:49 UTC
