### ISSUE TITLE
System slowdown

### ISSUE THREAD

**Issue by jaybosamiya** [raelgc/scudcloud#336] opened 2016-01-16 14:44 UTC
Recently, I started to notice slowdowns on my system, and the system sprung back to normal upon closing scudcloud. Upon further anaylsis, I realized that if I keep scudcloud running for a long enough time, without restarting it, it seems to start eating up more and more memory and cpu% (as indicated using `top`). Not sure what is causing this, but a code/memory profiling might help.

**Comment by raelgc** [comment] 2016-01-16 15:08
Hi @jaybosamiya and thanks for reporting this issue!

Can you tell me which distro, version, desktop environment are you using? Usually this is related to old version of `pyqt`.

**Comment by stieg** [comment] 2016-01-16 22:45
Here is an example of high resource usage on `Fedora release 23 (4.2.8-300.fc23.x86_64)`.  Notice that scudcloud is chewingup 500+ M of RAM

![screenshot from 2016-01-16 16-41-51](https://cloud.githubusercontent.com/assets/141519/12374870/45d5d316-bc70-11e5-8aa4-a6f61523095d.png)

```
Name        : python3
Version     : 3.4.3
Release     : 5.fc23
Architecture: x86_64
Install Date: Thu 01 Oct 2015 03:06:25 PM CDT
```

LMK what other info you may need.

**Comment by raelgc** [comment] 2016-01-17 10:39
About RAM usage: any Slack client is, actually, a web browser running the web version, as Slack doesn't have a public API to read messages.

About ScudCloud: in the past, few users complained about the memory usage increasing, like @jaybosamiya mentioned. But I cannot reproduce this on Ubuntu. I use with 2 teams, and I my RAM is 319 now, after 2 weeks. We think it's related to some component, but still didn't find the root cause.

If you guys, can help with profiling, maybe we can find the difference between our systems and find the cause.

Just worth to mention: @jaybosamiya maybe in this meanwhile, as all we need to use Slack in a daily basis, you can try the other 2 clients for Slack on Linux: [plaidchat](https://github.com/plaidchat/plaidchat) and the [official one](https://slack.com/downloads) too see if they don't have the same problem.

**Comment by jaybosamiya** [comment] 2016-01-17 17:48
Hi @raelgc. I use Ubuntu 14.04 LTS with effectively all the defaults (such as Unity and such). I keep it updated on a daily basis, so am pretty sure it isn't an old `pyqt` thing.

I understand that ScudCloud takes up some more memory in general since it is essentially a browser running the web version, however, the issue I have usually happens only when I keep it running for quite a long time. You might be right about it being related to some specific component which I probably use often.

My most commonly used tasks on slack include normal chat (which shouldn't be a problem, otherwise too many people would be complaining already), reactions (again, don't think this is it), large code snippets (could be an issue, especially when expanding past the few lines it normally shows), pictures (probably not an issue), videos (could be an issue, but then again, I think more might be complaining).

I might try out the other clients soon, just to check whether the problem lies in slack, or in scudcloud. However, I am not sure I'll be able to do that very soon (due to various reasons), so I'll stick to trying various different combinations of things and seeing if there are any spiking slowdowns for now.

Let me know if you need any more info :)

**Comment by raelgc** [comment] 2016-01-18 12:16
Nice report, @jaybosamiya! Very useful! :)

I use on 14.04 too (just waiting for 16.04).

Which we know it's a resource hog in current version of Slack + qtwebkit is large code snippets. Unfortunately, this is a known behaviour, duplicate of #140 (and reported at #253 too).

I'm trying, in my spare time, to port to Qt5, to check if the performance will improve a bit for this case.

So, please, check if this is the case for you too: resources blowing up on large code snippets.

**Comment by raelgc** [comment] 2016-01-22 22:18
Duplicate of #140.

**Closed as completed by raelgc** 2016-01-22 22:18 UTC

**Comment by raelgc** [comment] 2016-11-16 10:49
I just release a new version with an option to disable snippets (they'll be viewable in browser after click).

After upgrade, open your config file located at `~/.config/scudcloud/scudcloud.cfg` and add the following line:

```
Snippets=False
```
