### ISSUE TITLE
crash on startup - started today

### ISSUE THREAD

**Issue by waynestillman** [raelgc/scudcloud#346] opened 2016-01-25 19:47 UTC
$ scudcloud --debug DEBUG
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 2158, in _find_spec
AttributeError: 'DynamicImporter' object has no attribute 'find_spec'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/scudcloud/notifier.py", line 3, in <module>
    from gi.repository import Notify
  File "/usr/lib/python3/dist-packages/gi/importer.py", line 53, in find_module
    'introspection typelib not found' % namespace)
ImportError: cannot import name Notify, introspection typelib not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/scudcloud", line 9, in <module>
    load_entry_point('scudcloud==1.2.0', 'gui_scripts', 'scudcloud')()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 351, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2363, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2088, in load
    entry = **import**(self.module_name, globals(),globals(), ['**name**'])
  File "/usr/lib/python3/dist-packages/scudcloud/**main**.py", line 16, in <module>
    import scudcloud.scudcloud as sca
  File "/usr/lib/python3/dist-packages/scudcloud/scudcloud.py", line 3, in <module>
    from scudcloud.notifier import Notifier
  File "/usr/lib/python3/dist-packages/scudcloud/notifier.py", line 5, in <module>
    import notify2
ImportError: No module named 'notify2'

**Comment by waynestillman** [comment] 2016-01-25 19:53
Needed to install python3-notify2.
Not sure how that was missing....
No bug here.

**Comment by raelgc** [comment] 2016-01-25 21:13
Duplicate of #342. Already fixed. I was waiting to deploy other issues together, but you're the third reporting this in few hours.

**Closed as completed** 2016-01-25 21:15 UTC
