### ISSUE TITLE
#team channel isn't showing

### ISSUE THREAD

**Issue by davidwindell** [raelgc/scudcloud#464] opened 2016-06-28 09:00 UTC
We have a channel called #team, for some reason it won't show on any machine running Scudcloud but is fine in the web interface.

```
ScudCloud 1.26
Python 3.4.3
Qt 4.8.6
PyQt 4.10.4
SIP 4.15.5
```

**Comment by 0xd3adsh3ll** [comment] 2016-06-28 12:20
I have the same problem. In the client I don't see a channel #general sometime.
Description:    Linux Mint 17.2 Rafaela
ScudCloud 1.26-2
Also, after latest update I can't edit my own messages, after editing message I'm try click "Save change" but nothing happens.

**Comment by raelgc** [comment] 2016-06-28 12:21
Duplicate of #454

**Closed as completed by raelgc** 2016-06-28 12:21 UTC
