### ISSUE TITLE
Signed into multiple teams, no icon for one of them

### ISSUE THREAD

**Issue by ATeal** [raelgc/scudcloud#258] opened 2015-10-14 13:31 UTC
Hey guys firstly let me say that I definitely appreciate all the hard work that has gone into scud cloud and up until this week it has worked flawlessly. 

![image](https://cloud.githubusercontent.com/assets/5629145/10484958/267566e4-7256-11e5-8a94-02b673db0349.png)

I'm signed into two teams, but only one icon is showing for the other team. If I click into that team I have to go into the "Sign into another team" menu option which shows that I'm signed into both and then I can click the other team there. It doesn't seem to be widespread as other teamates aren't having the same issue. I've tried uninstalling and reinstalling, but no luck there. Any thing I can do to help resolve this let me know!

**Comment by raelgc** [comment] 2015-10-14 13:35
Hi @ATeal, thanks for reporting this issue.

If you remove the config folder (`~/.config/scudcloud`), and start to sign into teams again, the same happens?

**Comment by ATeal** [comment] 2015-10-14 13:38
Just gave that a go and the same problem persists. I have the one icon in the top left.

**Comment by raelgc** [comment] 2015-10-14 13:48
Thank @ATeal.

If you start `scudcloud` in the command line, can you see any error as output?

**Comment by ATeal** [comment] 2015-10-14 14:08
This is all I'm getting: 
![image](https://cloud.githubusercontent.com/assets/5629145/10486086/586eb3da-725b-11e5-9c5c-b381e0cc37d9.png)

I tried navigating around and whatnot to see if I could trigger an error. Turns out my coworker is now facing the same issue. I also forgot to mention I'm on Ubuntu 15.04 and he is on Ubuntu 14.04 LTS

**Comment by cgdeboer** [comment] 2015-10-14 14:15
Here is the dump from my `:~$ scudcloud`   

```
calvin@silversputnik:~$ scudcloud
No bp log location saved, using default.
[000:000] Cpu: 6.69.1, x4, 3000Mhz, 7508MB
[000:001] Computer model: Not available
[000:001] Browser XEmbed support present: 1
[000:001] Browser toolkit is not Gtk2 (0).
[000:001] Using Xt toolkit
No bp log location saved, using default.
[000:000] Cpu: 6.69.1, x4, 3000Mhz, 7508MB
[000:000] Computer model: Not available
Vector smash protection is enabled.
java version "1.7.0_79"
OpenJDK Runtime Environment (IcedTea 2.5.6) (7u79-2.5.6-0ubuntu1.14.04.1)
OpenJDK 64-Bit Server VM (build 24.79-b02, mixed mode)
SpellCheck: Language = "en_US" 
```

I am seeing the same behavior. I delete the `~/.config/scudcloud` directory and restarted. I noticed it was still logged into the teams, so I logged out of each of the teams in scudcloud, closed it down, then deleted the directory. When I launched again and resigned in, the selector sidebar is still not working as intended.

Many thanks for your help @raelgc

**Comment by raelgc** [comment] 2015-10-14 14:19
Just to share: close the app then delete config files after should be enough.

In your output, @cgdeboer, I can see the plugins starting for 2 teams.

So, just to double check:
- @ATeal can see the sidebar, but with an icon just for the second team;
- @cgdeboer cannot see the sidebar.

Is that correct?

**Comment by cgdeboer** [comment] 2015-10-14 14:29
I can see the sidebar, but just for one team. (just like ateal)

**Comment by ATeal** [comment] 2015-10-14 14:30
Correct for me @raelgc

**Comment by cgdeboer** [comment] 2015-10-14 14:46
![image](https://cloud.githubusercontent.com/assets/174766/10487059/25b62464-7260-11e5-9c2f-499b4999c48b.png)

Also, looks like my ubuntu native notifications and system tray are also gone :(

**Comment by raelgc** [comment] 2015-10-14 15:17
Can you guys, please, start ScudCloud this way:

```
scudcloud --debug=True &
```

Then, after ScudCloud finished to load, right click, select `Inspect`, maximize the window, and go to `Console`. Check the red error messages (paste them here).

**Comment by ATeal** [comment] 2015-10-14 15:37
No red error messages for me in the console :/

**Comment by cgdeboer** [comment] 2015-10-14 15:37
Here is are messages after ScudCloud loads. (everything looks peachy keen).

```
ran 398 of 398 tests. passed:398 failed:0

2015/10/14 11:33:14.633 booted! pri:0 rollup-core_required_ts.js:1
2015/10/14 11:33:14.633 489ms from first html to TS.boot() rollup-core_required_ts.js:1
2015/10/14 11:33:14.653 onDOMReady rollup-core_required_ts.js:1
2015/10/14 11:33:14.812 668ms from first html to calling onStarts() rollup-core_required_ts.js:1
2015/10/14 11:33:14.812 159ms from dom ready to calling onStarts() rollup-core_required_ts.js:1
2015/10/14 11:33:14.812 TS.storage.disabled:true rollup-core_required_ts.js:1
2015/10/14 11:33:14.838 going to call _backFillRxnRecords because ls_rxn_records.length:0 rollup-core_required_ts.js:1
2015/10/14 11:33:15.200 rtm.start included latest event timestamp: 1444836195.000000 rollup-core_required_ts.js:1
2015/10/14 11:33:15.206 open channels/groups/ims:15 initial_msgs_cnt:180 subsequent_msgs_cnt:360 special_initial_msgs_cnt:360 rollup-core_required_ts.js:1
2015/10/14 11:33:15.227 displayGroup horizon-lifeview from_history:false replace_history_state:true rollup-core_required_ts.js:1
2015/10/14 11:33:15.275 1131ms from first html to login_sig.dispatch() rollup-core_required_ts.js:1
2015/10/14 11:33:15.339 Connecting to: wss://ms355.slack-msgs.com/websocket/cF8OWxwMfeOuSYh_I7BHkTaiz-d4e25jbgLKw7…llel_rtm_start_rsp-1-1444836795&on_login-0-1444836795&connect-0-1444836795 rollup-core_required_ts.js:1
2015/10/14 11:33:15.558 MS WS connected! rollup-core_required_ts.js:1
2015/10/14 11:33:15.611 Hello msg recvd, since_last_pong_ms:1444836795611 rollup-core_required_ts.js:1
```

Then, when I click switch teams:

```
2
ReferenceError: Can't find variable: ScudCloud
3
Unrecognized Content-Security-Policy directive 'referrer'.
 [native code]:1
3
Unrecognized Content-Security-Policy directive 'referrer'.
 [native code]:1
7
ReferenceError: Can't find variable: TS
```

**Comment by cgdeboer** [comment] 2015-10-14 15:38
To clarify, the messages I posted last are indeed red, but only show up when I try to switch teams.

**Comment by ATeal** [comment] 2015-10-14 15:42
Just kidding, I'm experiencing the same thing after blowing away the `~/.config/scudcloud` directory and poking around signing in / out of teams:

![image](https://cloud.githubusercontent.com/assets/5629145/10488844/9abbaaba-7268-11e5-8e4e-1b20ef6b8f7c.png)

**Comment by raelgc** [comment] 2015-10-14 16:14
Just to double check: had you guys ran a `sudo apt-get update && sudo apt-get dist-upgrade` to get latest qtwebkit?

**Comment by cgdeboer** [comment] 2015-10-14 16:23
I have not explicitly done so, should I ?

**Comment by raelgc** [comment] 2015-10-14 16:31
@cgdeboer Yes, please. A lot of small issues got solved when upgrading to latest qtwebkit.

**Comment by cgdeboer** [comment] 2015-10-14 17:56
I did a `sudo apt-get update && sudo apt-get dist-upgrade` and restarted my box. Still seeing the error. Is there anything I can do to confirm my version of qtwebkit?

**Comment by filipeguarino** [comment] 2015-10-15 02:54
I have same problem here.. Ubuntu 15.04.. I did update and dist-upgrade, but the icon not appears yet. problem persist.

**Comment by raelgc** [comment] 2015-10-15 09:36
Maybe it's related to the left pane logic. And can be something trivial.

Is the team name or team URL for you using special chars, double quotes, maybe even blank space in the name?

**Comment by filipeguarino** [comment] 2015-10-15 11:26
@raelgc yes! the team name use hifen.

**Comment by raelgc** [comment] 2015-10-15 12:22
So, maybe I'll need your help to Inspect the left pane.

First, using `sudo` or `root`, edit `/opt/scudcloud/lib/leftpane.py` and comment the `contextMenuEvent` method like this:

``` python
#    def contextMenuEvent(self, event):
#        pass
```

Then start ScudCloud in debug mode:

```
scudcloud --debug=True &
```

Then check the console in the left pane.

In case some of you want to try dig-hack-fix the LeftPane js, copy the `leftpane-src.js` [from the repo](https://github.com/raelgc/scudcloud/tree/master/scudcloud-1.0) and save as `/opt/scudcloud/resources/leftpane.js` (you'll need `sudo`/`root` privileges). 

Then, as `sudo`/`root`, edit, save and restart the app.

**Comment by cgdeboer** [comment] 2015-10-15 12:33
Ha Ha, We had an apostrophe and a space....whoops. That fixed it.

Easy fix...changed the name. :boom:

Thanks @raelgc

**Comment by raelgc** [comment] 2015-10-15 12:46
@cgdeboer makes sense: the single quote is breaking the code. I'm preparing a fix for this.

**Comment by raelgc** [comment] 2015-10-15 16:23
I've published a new version for all supported Ubuntu flavors. If, after upgrade, this is still an issue, please, re-open this bug.

**Closed as completed by raelgc** 2015-10-15 16:23 UTC
