### ISSUE TITLE
Channels sidebar only has one item

### ISSUE THREAD

**Issue by cheskos** [raelgc/scudcloud#554] opened 2017-04-06 20:28 UTC
## ScudCloud Version

Paste the output for `scudcloud --version` below:
ScudCloud 1.50
Python 3.6.0
Qt 5.8.0
PyQt 5.8
SIP 4.19.1

## Distro and Desktop info

  - Distribution: Arch
  - Version/Release: 4.10.8-1-ARCH
  - Desktop environment: MATE

## Expected behavior

Channels which I'm signed in should appear on the sidebar

## Actual behavior

Only one team shows up

## Steps to reproduce
 1. Login to seveal team
 2. Watch how only one remains
 3. Cry in fetal position

**Comment by raelgc** [comment] 2017-04-06 20:47
Hi @cheskos and thanks for reporting this issue.

It happens all the times or randomly? (I got this sometimes under slow connections).

**Comment by cheskos** [comment] 2017-04-06 20:50
Well, the system is recently installed, and the slowness is possible. Will try out at home and report back. Thank you.

**Comment by cheskos** [comment] 2017-04-06 21:27
Already tried on a better connection, problem is still there. Good thing though: the missing channels are added after a restart.

**Comment by raelgc** [comment] 2017-04-06 21:53
Yeap, I had to restart when this happens too. The problem is: I still didn't face this while opening ScudCloud with debug mode enabled (to follow the Slack responses when this happens).

**Comment by shevek** [comment] 2017-04-10 01:34
Affects me too: I had 9 teams, now I only have one.

**Comment by shevek** [comment] 2017-04-10 01:35
Restart caused all 9 teams to show up again.

**Comment by raelgc** [comment] 2017-04-10 11:22
I found the root cause and a solution for this. I'll publish in the next hours.

**Comment by raelgc** [comment] 2017-04-10 12:03
I pushed a fix for it. A lot of times, Slack do not return the complete teams info at startup, just few milliseconds later. This was broking the team loading at Scudcloud. I've made a check, during the startup, if the teams info is not ready, let's check again in 0.5 second (and check again 0.5 second later) until we get all teams info.

**Comment by raelgc** [comment] 2017-04-11 19:48
This should be fixed now. Let me know if still an issue.

**Closed as completed by raelgc** 2017-04-11 19:48 UTC
