### ISSUE TITLE
Scudcloud does not work on Gentoo Linux

### ISSUE THREAD

**Issue by jvican** [raelgc/scudcloud#383] opened 2016-02-08 17:43 UTC
Hi! So I got a problem when running Scudcloud.

There's a package for Gentoo. I installed it and tried it out. It's not working. The logs only say that the murrine and adwaita themes haven't been found. I am running dwm (Dynamic Window Manager) but I do have support for both any graphics library.

The problem is the application gets stuck in the process of loading the slack channel. Until that point everything seems ok. I have tried to download the last version (1.9) and install it manually. Same problem. If I remove the `.config/scudcloud`, the application does try to load the same channel again without asking me to introduce the new data (I was surprised about this, I was expecting it to ask me again for my credentials).

What valuable info could I give you? I run Python 3.4. BTW, I'm using firefox with firejail... I hope this is not the root of the problem. Firejail cuts a lot of permission for stuff but I hope that you app is not using my browser for anything than opening links.

Cheers

**Comment by raelgc** [comment] 2016-02-08 20:39
If you'll remove `.config/scudcloud`, you have to close the application first. If not, data is loaded in memory, then saved after close it.

No, ScudCloud only read config file and team icons saved in temp folder (they're saved by ScudCloud itself).

**Comment by raelgc** [comment] 2016-02-08 20:40
Duplicate of #335

**Closed as completed by raelgc** 2016-02-08 20:40 UTC
