### ISSUE TITLE
Having to confirm login to my team every time I open Scudcloud.

### ISSUE THREAD

**Issue by cdysthe** [raelgc/scudcloud#475] opened 2016-07-05 16:38 UTC
I'm running Scudcloud 1.30-2 on Ubuntu GNOME 16.04.

Every time I open Scudcloud I'm at the login screen asked if I want to sign in to another team and also: 

You're already signed in to this team:

[Team Name] 

I used to get straight into my (only) team, but no I am taken on this detour. This is not the case on the native Slack client, but I prefer Scudcloud so it would be great if this could be fixed.

**Comment by raelgc** [comment] 2016-07-05 16:44
Hi @cdysthe, thank you for reporting this.

Unfortunately, this is duplicate of #435.

**Closed as completed by raelgc** 2016-07-05 16:44 UTC
