### ISSUE TITLE
GTK warnings on Ubuntu 16.04

### ISSUE THREAD

**Issue by shevek** [raelgc/scudcloud#460] opened 2016-06-25 01:06 UTC
/usr/lib/python3/dist-packages/scudcloud/notifier.py:3: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Notify
/usr/lib/python3/dist-packages/scudcloud/scudcloud.py:27: PyGIWarning: Unity was imported without specifying a version first. Use gi.require_version('Unity', '7.0') before import to ensure that the right version gets loaded.
  from gi.repository import Unity, Dbusmenu

ii  scudcloud                                     1.26-2                                              all          ScudCloud is a non official desktop client for Slack
## ScudCloud Version

shevek@raven:~$ scudcloud --version
/usr/lib/python3/dist-packages/scudcloud/notifier.py:3: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Notify
/usr/lib/python3/dist-packages/scudcloud/scudcloud.py:27: PyGIWarning: Unity was imported without specifying a version first. Use gi.require_version('Unity', '7.0') before import to ensure that the right version gets loaded.
  from gi.repository import Unity, Dbusmenu
ScudCloud 1.26
Python 3.5.1+
Qt 4.8.7
PyQt 4.11.4
SIP 4.17
## Distro and Desktop info
- Distribution:Ubuntu
- Version/Release:16.04
- Desktop environment:xfce
## Steps to reproduce
1. 
2. 
3.

**Comment by raelgc** [comment] 2016-07-01 10:52
Duplicate of #288. While those warnings are a pain to see in 16.04, the problem: to fix them, I need to specify a version for few importing, and this will break on 12.04.

I someone candidate to keep the 12.04 version, I can go ahead and fix it. If not, I'll maintain this way until 12.04 got no more supported next year.

**Closed as completed by raelgc** 2016-07-01 10:52 UTC
