### ISSUE TITLE
Any plans to integrate it with corporate SSO?

### ISSUE THREAD

**Issue by egd-io** [raelgc/scudcloud#211] opened 2015-08-18 15:52 UTC
My corporate Slack requires SSO and Scudcloud is not compatible.  Just wondering if there was plans to incorporate this in the future?

**Comment by lenrok258** [comment] 2015-09-09 07:42
+1 for this question.
For the time being it is not possible to log in. Please let me know if you need more details.

**Comment by raelgc** [comment] 2015-09-09 11:00
Hi @eth-0 and @lenrok258, sorry for my late response.

What happens when you try the SSO auth? Can you give me a sample URL?

I'm asking because in theory this was fixed in #44

**Comment by lenrok258** [comment] 2015-09-09 11:40
Hi @raelgc, 

here is scenario to reproduce the problem:
1. Launch application 
2. Put 'ocado' as Slack domain
3. Click on 'Continue' button
4. 'Sign in with Google' button appears but nothing happens after clicking it. In debug mode I can see that 302 returns from server but it looks like app doesn't follow redirect.

I hope it helps.

**Comment by raelgc** [comment] 2015-09-09 12:39
I got this:

![](http://i.imgur.com/Ds8TyZk.png)

**Comment by lenrok258** [comment] 2015-09-09 13:37
Ok, so it seems that a problem is after authorization being complete. Unfortunately I can't give you any test user... so you will not be able to reproduce it.

**Comment by raelgc** [comment] 2015-09-09 13:41
Do you know which is the URL fired in 302 that is not followed?

**Comment by egd-io** [comment] 2015-09-09 21:23
I was able to find a work around that should probably be opened as another issue because it is a security concern.  I logged into the corporate Slack via Scudcloud on a laptop before SSO was enabled.  I later tried to sign in on a desktop after SSO was implemented and couldn't.  That's when I submitted this issue.  

After no response, I decided to try taking the config from the laptop and copy it to the desktop.  I did so and I was signed in to all the accounts I was signed into on the laptop.  While that was a work around to fix my issue, it is an incredibly insecure one.

**Comment by raelgc** [comment] 2015-09-10 00:03
The config file has the browser session, for this reason is saved in your personal config folder, under your home.

**Comment by raelgc** [comment] 2015-09-10 00:12
Anyway, @eth-0, waiting for the sample URL that is firing the 302.

In this meanwhile, as probably you cannot wait for a fix (as I imagine you're using for work), you can subscribe for the official Slack client beta for Linux (they've sent me few days ago): https://docs.google.com/forms/d/1uOlDiuT9XMEGijhXicsOasJv3Nxvt5Azvd9OIIS61Sk/viewform

**Comment by lenrok258** [comment] 2015-09-10 08:18
Hi @raelgc,

I've found workaround that works for me. I've disconnected from my company's internal network (where SSO should authenticate me automatically after clicking on (mentioned before) 'Sign in with Google' button) and connected to the Internet somewhere else. After doing it I was able to see the same screen as you and I was able to sign-in. 

Nevertheless thanks for your support.

**Comment by raelgc** [comment] 2015-09-10 10:53
@lenrok258 I'm glad to hear it worked!

Sounds like some company proxy was redirecting and ScudCloud was not following the redirect.

Thank you for pointing a workaround! This will be valuable for more people reporting this issue!

**Closed as completed** 2015-10-02 11:43 UTC
