### ISSUE TITLE
ScudCloud desktop notifications

### ISSUE THREAD

**Issue by jgrandef** [raelgc/scudcloud#195] opened 2015-08-05 19:21 UTC
When desktop notifications are sent to Ubuntu 14.04 desktop, instead of containing a blurb of the message text the message text appears as:

function() { TS.ims.startImByMemberId
(h.user);
}

![image](https://cloud.githubusercontent.com/assets/7441905/9095508/9604b544-3b85-11e5-9067-d9e5805bc7a5.png)

**Comment by stieg** [comment] 2015-08-05 20:03
+1 to this on Fedora 22.  Here is package info:

```
$ rpm -qi scudcloud
Name        : scudcloud
Version     : 1.0.36
Release     : 2.fc22
Architecture: noarch
Install Date: Sun 02 Aug 2015 09:00:36 PM MDT
Group       : Unspecified
Size        : 221036
License     : MIT
Signature   : RSA/SHA1, Wed 10 Jun 2015 10:10:27 AM MDT, Key ID f7daa26b5021d4d4
Source RPM  : scudcloud-1.0.36-2.fc22.src.rpm
Build Date  : Wed 10 Jun 2015 10:10:00 AM MDT
Build Host  : copr-builder-49596892
Relocations : (not relocatable)
Vendor      : Fedora Project COPR (jsbillings/scudcloud)
```

**Comment by jgrandef** [comment] 2015-08-05 20:10
From the original ticket:

Ubuntu 14.04

Package: scudcloud
Status: install ok installed
Priority: optional
Section: utils
Installed-Size: 310
Maintainer: Rael Gugelmin Cunha rael.gc@gmail.com
Architecture: all
Version: 1.0-53
Depends: libqtwebkit4 (>= 2.3.2), python3, python3-dbus, python3-pyqt4,
xdg-utils
Recommends: sni-qt, fonts-lato, gir1.2-unity-5.0,
libqtwebkit-qupzillaplugins, python3-gi, ttf-mscorefonts-installer
Description: ScudCloud is a non official desktop client for Slack
 ScudCloud is a non official desktop client for Slack.
 Slack (http://slack.com) is a platform for team communication.
Homepage: https://github.com/raelgc/scudcloud

**Comment by stieg** [comment] 2015-08-05 20:32
Just tried this with commit 8ece6f57f4c53e2a6b745ecede9975e1c825a236 and saw the same behavior as well.

**Comment by roman-kiselenko** [comment] 2015-08-05 20:40
@jgrandef  Ubuntu 14.04 reinstall help me, but now i have https://github.com/raelgc/scudcloud/issues/192

**Comment by stieg** [comment] 2015-08-05 20:46
Unfortunately running `sudo dnf reinstall scudcloud` did not yield any
difference for me.

On Wed, Aug 5, 2015 at 2:40 PM, Philidor Green notifications@github.com
wrote:

> @jgrandef https://github.com/jgrandef Ubuntu 14.04 reinstall help me,
> but now i have #192 https://github.com/raelgc/scudcloud/issues/192
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/raelgc/scudcloud/issues/195#issuecomment-128141707.

## 

Andrew AV. Stiegmann

**Comment by mikolak-net** [comment] 2015-08-06 08:03
@jgrandef: This looks like a duplicate of #193 . That issue was fixed in 1.0-54 (is now available in the PPA).

@stieg: the relevant fix commit appears to be 76f9e78171db03f8171ccf260bf2953c76d571d6 .

**Comment by raelgc** [comment] 2015-08-06 14:07
Please, upgrade to 1.0.54. If you're using `apt`, run a `sudo apt-get update`.

**Closed as completed by raelgc** 2015-08-06 14:07 UTC

**Comment by jgrandef** [comment] 2015-08-06 14:20
Thank you @raelgc . After update notifications seem to be working properly again. Thanks for the quick response.

**Comment by stieg** [comment] 2015-08-06 16:45
@raelgc That did the trick for me as well.  Thanks.

**Comment by moonwolf-github** [comment] 2015-08-10 06:34
@stieg you may try to use my repo as i just added F22 to the builds (see [these instructions](http://software.opensuse.org/download.html?project=home%3Amoonwolf%3Ascudcloud&package=scudcloud)). Note - i'm still on F21 so it's untested.

**Comment by stieg** [comment] 2015-08-10 14:57
Thanks @moonwolf-github.  I'll give it a shot.

**Comment by paoloantinori** [comment] 2015-09-23 10:34
SOLVED:
https://github.com/raelgc/scudcloud/issues/207

# 

Hi guys, I have just tried to install scucloud on fedora, using `home_moonwolf_scudcloud` repo.

It installs fine but I never get to see scucloud app, just the window frame.

Any suggestion on how to fix this?

I see it beeing at `v1.0.69-1.1`

Running it from command line I can see these logs:

```
$ scudcloud 
loaded the Generic plugin 
/usr/bin/scudcloud:38: Warning: cannot register existing type 'GdkDisplayManager'
  sys.exit(app.exec_())
/usr/bin/scudcloud:38: Warning: g_once_init_leave: assertion 'result != 0' failed
  sys.exit(app.exec_())
/usr/bin/scudcloud:38: Warning: g_object_new: assertion 'G_TYPE_IS_OBJECT (object_type)' failed
  sys.exit(app.exec_())
```

**Comment by raelgc** [comment] 2015-09-23 11:17
Maybe we should turn off the Flash plugin by default.

**Comment by moonwolf-github** [comment] 2015-09-23 12:19
Tomorrow i'll install F22 on VM and test it.

**Comment by moonwolf-github** [comment] 2015-09-23 13:46
I managed to install it today. Can confirm issue now, but don't know the solution (scudcloud --no_plugins=True works but it's a workaround). What about flash plugin? Is it used for anything anyway?

**Comment by mbajor** [comment] 2015-09-23 16:07
@paoloantinori @moonwolf-github Tested on F22. Please upgrade Fedora
yum upgrade
Note that scudcloud is build always with newest packages

**Comment by raelgc** [comment] 2015-09-23 16:47
@moonwolf-github Only for Youtube videos that will be played inside Slack. I.e., probably we can disable by default and nobody will notice it.
