### ISSUE TITLE
High CPU usage on text snippets

### ISSUE THREAD

**Issue by iddqdidkfa** [raelgc/scudcloud#261] opened 2015-10-16 09:24 UTC
Tried to expand in chat text snippet with 300 lines of plain text and application becomes extremely slow.
Resources monitor shows 90% usage of python3 process. It's not a first time I face such problem with text snippets, just a first time I decide to share my pain :)

In Slack Linux Beta no problems with same text snippet.

**Comment by raelgc** [comment] 2015-10-16 10:40
Hi @iddqdidkfa, thanks for reporting this.

Unfortunately, this is a known behaviour, duplicate of #140 (and reported at #253 too).

If you brave enough, you can test the [Qt5 port](https://github.com/raelgc/scudcloud/tree/254-port-to-qt5), but still has some issues (like no systray and no red mark for bad spelled words).

**Closed as completed** 2015-10-16 10:40 UTC

**Comment by iddqdidkfa** [comment] 2015-10-16 13:27
No systray is not an option xD
So you think Slack Linux Beta not using webkit for rendering?

**Comment by raelgc** [comment] 2015-10-16 14:07
They're using `electron`, which uses Chromium internally. Good performance (as it has a newest JavaScript engine), but terrible RAM usage.

We can work in a systray icon for Qt5 version, it just requires to use `libindicator` on Unity directly, as the `Qt` way is no more supported.

**Comment by iddqdidkfa** [comment] 2015-10-16 14:59
Yeah I have noticed Slack Linux uses about 150 Mb for each team on start. But `python3` process in ScudCloud growing with time (I had about 600 Mb after 3 days uptime), probably because of cache.
You mean Unity desktop environment? I'm on Mate and have no plans to use Unity. Does it mean spellchecker plugin is the only one problem for me for using Qt5 version?

**Comment by raelgc** [comment] 2015-10-16 15:34
@iddqdidkfa Mate is Gtk, so probably the tray icon will **NOT** work too without new tray icon code.

**Comment by raelgc** [comment] 2015-10-17 10:15
@iddqdidkfa I got ScudCloud running for 4 days here... 2 very active teams, 1 almost inactive... never get more than 300Mb RAM usage. Appears this can be related to the python version. Which version are you using?

**Comment by iddqdidkfa** [comment] 2015-10-17 14:21
Python 3.4.3
![system-monitor](https://cloud.githubusercontent.com/assets/1819727/10559192/7318cece-74f3-11e5-988d-edfc8d382629.png)

I got 1 not much active team (but GitLab bot posting commits too channel 5-10 times per hour) and 1 almost inactive team

**Comment by raelgc** [comment] 2015-10-17 23:13
Hm... my guess: can be related to some native library not used in your side; or Mate using some old GTK library (used in notifications), while Unity uses GTK 3.

**Comment by raelgc** [comment] 2016-11-16 10:49
I just release a new version with an option to disable snippets (they'll be viewable in browser after click).

After upgrade, open your config file located at `~/.config/scudcloud/scudcloud.cfg` and add the following line:

```
Snippets=False
```
