### ISSUE TITLE
Last signed in Slack account does not persist

### ISSUE THREAD

**Issue by davereid** [raelgc/scudcloud#206] opened 2015-08-12 14:41 UTC
I keep having to sign into fourth Slack account. Whenever I restart the application the fourth account never persists. I do have the 'Remember me' checked when I sign in every time.

**Comment by davereid** [comment] 2015-08-17 14:55
Hrm, this seems to be happening to whatever Slack account I signed into _last_. It never persists beyond my current application session.

**Comment by raelgc** [comment] 2015-08-17 19:50
Hi @davereid, thanks for reporting this issue.

I'm trying to wonder the reason for this. ScudCloud persists the browser session in config files. Maybe there is a limit for this.

Do you mind to delete your `~/.config/scudcloud` folder and try again?

Hope we can find the reason for this problem and fix it! :)

**Comment by davereid** [comment] 2015-08-21 16:08
I'll give that a try starting next week since I'm not looking forward to having to re-auth 5 different accounts with TFA on a Friday. :)

**Comment by RoverWire** [comment] 2015-08-28 18:47
Hey, this is a workaround that seems to work https://github.com/raelgc/scudcloud/issues/199#issuecomment-132975073

**Comment by raelgc** [comment] 2015-09-03 11:42
Duplicate of #199

**Closed as completed by raelgc** 2015-09-03 11:42 UTC
