### ISSUE TITLE
Preferences action in menu always open in first team

### ISSUE THREAD

**Issue by madjidtaha** [raelgc/scudcloud#131] opened 2015-06-01 16:39 UTC
Hello,

I use Scudcloud on elementary OS Freya with multiple team,
when I try to open preferences in my second team, nothing happen and when I switch to my first team,
the preferences panel is open.

Maybe the #125 issue is linked to it.

Thank you

**Comment by raelgc** [comment] 2015-06-10 13:43
Duplicate of #125

**Closed as completed by raelgc** 2015-06-10 13:43 UTC
