### ISSUE TITLE
ScudCloud always displays the loading screen

### ISSUE THREAD

**Issue by Slater91** [raelgc/scudcloud#294] opened 2015-11-18 22:19 UTC
I've been experiencing a nasty issue since today evening. ScudCloud simply does not go beyond the loading screen and does in fact lock the user out. 
The terminal returns no errors whatsoever, not even in debug mode. Slack (meant as the service itself) is otherwise running fine; it works okay using the web client (under Firefox 42), the official Linux client (which, by the way, is by far worse than ScudCloud) and the mobile app. I tried deleting the configuration folder, but to no avail.
I do not know whether this problem is just momentary or if it is permanent, but I think it may be better to take note of the problem now so investigations can possibly take place if it is confirmed.

**Comment by opokhvalit** [comment] 2015-11-18 23:15
I see the same problem :( One important difference: today I updated to Ubuntu 15.10 (from 15.04) and cannot login since this update
Slack works well from firefox browser. I tried to remove configs and Trolltech.conf - no luck, I have got login screen in scudcloud, did  authentification and see continuous loading screen....

**Comment by heliomeiralins** [comment] 2015-11-19 00:01
I'm experiencing the same issue.

**Comment by jnankin** [comment] 2015-11-19 00:06
Yep, me too!  This is what I see when starting from the terminal:

"sni-qt/4972" WARN  18:05:42.647 void StatusNotifierItemFactory::connectToSnw() Invalid interface to SNW_SERVICE 
No bp log location saved, using default.
[000:000] Cpu: 16.2.3, x4, 2200Mhz, 5842MB
[000:000] Computer model: Not available
[000:000] Browser XEmbed support present: 1
[000:000] Browser toolkit is not Gtk2 (0).
[000:000] Using Xt toolkit
No bp log location saved, using default.
[000:000] Cpu: 16.2.3, x4, 2200Mhz, 5842MB
[000:000] Computer model: Not available
Vector smash protection is enabled.

(python3:4972): Gdk-WARNING **: /build/gtk+2.0-qOsbtf/gtk+2.0-2.24.10/gdk/x11/gdkproperty-x11.c:325 invalid X atom: 500

**Comment by boltronics** [comment] 2015-11-19 00:19
Haven't been able to connect since I got into work this morning, over 3 hours ago. Can load it in my browser fine, but that's impractical.

**Comment by jamespepplinkhouse** [comment] 2015-11-19 00:28
I've got the same issue. So far I've deleted my ~/.config/scudcloud directory and then removed and reinstalled ScudCloud which didn't help.

**Comment by raelgc** [comment] 2015-11-19 01:20
I started to get the same here too. But, of course, I changed nothing on ScudCloud. Let me see if I can try any workaround.

**Comment by goper-leo** [comment] 2015-11-19 02:01
Same issue here in Ubuntu 14.04.

**Comment by heliomeiralins** [comment] 2015-11-19 02:20
I installed the plaidchat client, and it's working fine.

**Comment by jsvachon2** [comment] 2015-11-19 02:49
I'm having the same issue here on Ubuntu 15.10. No error message but stuck with the Loading screen

**Comment by heliomeiralins** [comment] 2015-11-19 02:54
Could it be related to the User Agent HTTP header?

**Comment by benwaffle** [comment] 2015-11-19 04:04
I get `TypeError: 'null' is not an object (evaluating '_ls.getItem')` in file `rollup-secondary_a_required.js:1` in the console, if that helps

**Comment by jamespepplinkhouse** [comment] 2015-11-19 04:17
+1 for plaidchat

**Comment by jnankin** [comment] 2015-11-19 04:21
plaidchat may be working, but that does not fix scudcloud

**Comment by thatguy764** [comment] 2015-11-19 05:01
1. Fork Plaidchat
2. Rename fork Scudcloud
3. ????
4. Issue resolved!

**Comment by rask** [comment] 2015-11-19 06:31
Getting the same issue here. Ubuntu 14.04 and ScudCloud reports version 1.0.89. Keeps getting stuck on the loading "spinner" . Let me know if there is anything else you need to help get this solved.

**Comment by pvarabyou** [comment] 2015-11-19 07:16
+1

**Comment by daris** [comment] 2015-11-19 07:44
It also stopped working for me, stuck at loading screen, Ubuntu 15.04

**Comment by puittenbroek** [comment] 2015-11-19 07:47
Same here, Ubuntu 14.04. Tried:
- Removing config
- Reinstall scudcloud
- Remove + purge + reinstall scudcloud

No (relevant) errors when booting from CLI.

**Comment by dorian-marchal** [comment] 2015-11-19 08:13
Same here, on my two Ubuntu 14.04 (Unity).

Scudcloud is stuck on the loading screen :
![capture du 2015-11-19 09 07 14](https://cloud.githubusercontent.com/assets/6225979/11265505/fa88adf8-8e9c-11e5-8f51-182ebc615113.png)

Init log :

```
No bp log location saved, using default.
[000:000] Cpu: 6.60.3, x8, 3900Mhz, 7912MB
[000:001] Computer model: Not available
[000:001] Browser XEmbed support present: 1
[000:001] Browser toolkit is not Gtk2 (0).
[000:001] Using Xt toolkit
No bp log location saved, using default.
[000:000] Cpu: 6.60.3, x8, 3900Mhz, 7912MB
[000:000] Computer model: Not available
Vector smash protection is enabled.
SpellCheck: Language = "fr_FR"
```

Console :
![capture du 2015-11-19 09 10 51](https://cloud.githubusercontent.com/assets/6225979/11265566/74152a84-8e9d-11e5-8282-8d7828cce979.png)

**Comment by dizzythinks** [comment] 2015-11-19 08:14
For what its worth it's broken for me too this morning. This is what I get when launching from the cli

Got bus address:  "unix:abstract=/tmp/dbus-M9KctBOjDZ,guid=2668a7aefc4786ec276317e5564d8220" 
Connected to accessibility bus at:  "unix:abstract=/tmp/dbus-M9KctBOjDZ,guid=2668a7aefc4786ec276317e5564d8220" 
Registered DEC:  true 
Registered event listener change listener:  true 
Vector smash protection is enabled.

Ubuntu 15, trusty, Gnome3, All updates, I also just updated scudcloud too.

**Comment by dmitraver** [comment] 2015-11-19 08:27
Same for me. Ubuntu 14.04 LTS. Also tried to delete config but it doesn't help.

**Comment by AramLoosman** [comment] 2015-11-19 08:50
Same here, Ubuntu 15.10

```
TypeError: 'null' is not an object (evaluating '_ls.getItem')
```

**Comment by buma** [comment] 2015-11-19 08:53
Same for me today on Arch. Didn't update anything. It worked yesterday. Now only web client works.

If anybody can tell me how to get SSL private key from scudcloud I can use Wireshark to log network traffic.

**Comment by Zpeedy** [comment] 2015-11-19 09:06
Slack's own beta Linux client works for me under Mint 17.2/64

**Comment by Jean85** [comment] 2015-11-19 09:27
Same here on Ubuntu 15.04 :(

**Comment by pvarabyou** [comment] 2015-11-19 09:28
Moved to Slack's app. Goodbye.

**Comment by pedzed** [comment] 2015-11-19 09:30
It doesn't work for me either on Ubuntu 15.10. I am now using the beta client for Linux (https://slack.com/downloads).

**Comment by oyagev** [comment] 2015-11-19 09:54
Same for me, ubuntu 14.04

**Comment by Jean85** [comment] 2015-11-19 10:26
Moved to Slack official beta app, I fear that they killed Scud voluntarely :(

**Comment by opokhvalit** [comment] 2015-11-19 10:37
Slack official beta does not work for me.

**Comment by weirdobeaver** [comment] 2015-11-19 10:55
Too bad cause scud client was working better

**Comment by dorian-marchal** [comment] 2015-11-19 11:03
> Too bad cause scud client was working better

:+1:

**Comment by raelgc** [comment] 2015-11-19 11:10
I can see they (Slack) changed/upgraded something in their JavaScript. And the webkit JS engine is failing to run the new JS, so it stuck in loading screen.

You can see the failures starting ScudCloud with: `scudcloud --debug=True &`, then right click and select `Inspect`, maximize the Inspector, and go to `Console`.

**Comment by raelgc** [comment] 2015-11-19 11:37
About plaidchat: for sure it's great, and I've even created an issue few days ago in their repo, suggesting we should join forces. They said they have no more interest in maintain the code, as now there is an official client.

**Comment by raelgc** [comment] 2015-11-19 11:38
Ok, I think I've fixed locally. I'll publish the new version in few minutes.

**Comment by sirMackk** [comment] 2015-11-19 11:40
@raelgc Thanks for pushing out the fix so quickly! Im sure Im not the only one who appreciates the time and work you've put into this :tada:

**Comment by sarxos** [comment] 2015-11-19 11:41
Great :) Can't wait for the fix! :+1:

**Comment by mbajor** [comment] 2015-11-19 11:44
@raelgc Could you create release version? I want to update openSUSE and Fedora repos.

**Comment by raelgc** [comment] 2015-11-19 11:55
@mbajor Sure, in few minutes! Let me just check if the uploaded package for Ubuntu will work fine, then I'll create the new release.

**Comment by sarxos** [comment] 2015-11-19 12:02
@raelgc, just FYI, after I modified my local copy of `lib/scudcloud.py` with only the line from your fix, I was able to log in. Seems to be working well.

**Comment by raelgc** [comment] 2015-11-19 12:03
@sarxos Thank you for sharing this info! I'm publishing a lot of improvements too that I worked in the last days.

**Comment by raelgc** [comment] 2015-11-19 12:19
@mbajor I've just published the new release!

**Comment by oyagev** [comment] 2015-11-19 12:24
Works!!
Thanks a lot!

**Comment by opokhvalit** [comment] 2015-11-19 12:24
cool! Could you please publish build for Ubuntu 15.10 (wily)?

**Comment by henriklindgren** [comment] 2015-11-19 12:25
Awesome! Got it from update now on Linux Mint 17.2.

**Comment by raelgc** [comment] 2015-11-19 12:27
@opokhvalit I've already fired the building in Launchpad for all supported Ubuntu versions, it's already done, just waiting to get published. Usually it takes 10 minutes.

**Comment by opokhvalit** [comment] 2015-11-19 12:31
Thanx! I'm very impatient and installed package from trusty. It works. This is amazing - you made fix very fast!

**Comment by mbajor** [comment] 2015-11-19 12:48
@raelgc Thanks! openSUSE and Ferora repos updated. Fix tested on openSUSE Thumbleweed - works fine:)

**Comment by Slater91** [comment] 2015-11-19 13:59
Hey @raelgc, thank you for the quick fix! You've been quicker to fix the issue than Slack was to replying to an unrelated support request. Keep up the good work!

**Comment by lube8uy** [comment] 2015-11-19 14:04
Thanks @raelgc working on ubuntu 14.04

**Comment by heliomeiralins** [comment] 2015-11-19 14:40
Working great on Arch. Thank you!

good luck for people migrating to the official client. It uses ~2GB of my memory, while scudcloud uses 300mb with the same channels. ( and plaidchat a little more than that)

**Comment by snebel29** [comment] 2015-11-19 14:42
Working fine, than ks for the quick fix!

**Comment by zerthimon** [comment] 2015-11-19 14:42
Had the same issue in Ubuntu 14.04
The update helped, thanks!

**Comment by brad** [comment] 2015-11-19 16:01
Thanks a million for the quick fix! Just upgraded from the PPA and it's working again.

**Comment by rsyring** [comment] 2015-11-19 16:32
Ditto on the thanks for the quick fix.

**Comment by ssergiienko** [comment] 2015-11-19 16:53
Thanks @raelgc ! Fixed in ArchLinux too.

**Comment by rblakemesser** [comment] 2015-11-19 18:29
@raelgc Thanks for the fix. I'm also not getting the update on Wily. Should just be `sudo apt-get update && sudo apt-get -y upgrade scudcloud`, right?

**Comment by brianphillips** [comment] 2015-11-19 18:48
@rblakemesser - I had the same issue.  Turns out the ppa was disabled when I upgraded to Wily a few weeks back.  After re-adding the PPA, it worked fine.

**Comment by rblakemesser** [comment] 2015-11-19 19:27
Oh yup that was it-- thanks guys

**Comment by boltronics** [comment] 2015-11-19 22:45
Nice job getting this sorted. :+1:

**Comment by goper-leo** [comment] 2015-11-20 05:30
@raelgc Thanks!

**Comment by dmitraver** [comment] 2015-11-20 08:28
@raelgc Thanks!

**Comment by svozza** [comment] 2015-11-20 09:48
Great stuff. Thank you! Btw, this is what I had to do:

``` sh
sudo apt-add-repository -y ppa:rael-gc/scudcloud && sudo apt-get update && sudo apt-get -y upgrade scudclou
```

**Comment by buma** [comment] 2015-11-20 12:32
Thanks it works for me too.

**Comment by josephlbarnett** [comment] 2015-11-21 05:45
It was working earlier today but now seeing the same problem again

**Comment by aekondratiev** [comment] 2015-11-21 08:17
Yep, doesn't work any more - ScudCloud 1.1.0 , yesterday was ok :)

**Comment by zerthimon** [comment] 2015-11-21 10:01
Confirmed.
The problem returned.

**Comment by raelgc** [comment] 2015-11-21 16:37
Please, upgrade.

**Comment by buma** [comment] 2015-11-23 08:44
Version 1.1.1 works again. Thanks!

**Comment by alfredopalhares** [comment] 2015-11-23 13:39
Just upgraded too. Fixed the problem. Thanks :+1:

**Comment by felixgilles** [comment] 2015-11-23 13:40
Many thanks !

**Comment by truckingsim** [comment] 2015-11-23 16:00
Can confirm upgrade fixed issue :+1:

**Comment by nuk** [comment] 2015-11-23 16:33
Same here, all working fine after upgrade :+1:

**Comment by ryanmaclean** [comment] 2015-11-23 20:08
Thanks for the quick fix! :metal:

**Comment by felixgilles** [comment] 2015-11-23 20:43
Hi,

Version 1.1.1 was working fine this afternoon at office, but now, at home, I always loading screen:

```
POST https://xxx.slack.com/api/rtm.start?xxxxxx 429 (Too Many Requests) [native code]:1
2015/11/23 21:38:11.163 api call "rtm.start" not ok 
```

:disappointed:

**Comment by jnankin** [comment] 2015-11-23 20:44
Be advised, slack is also having connectivity issues now in general, so it
might not be the client

**Comment by felixgilles** [comment] 2015-11-23 20:45
You've right, I try in Firefox, same issue

**Comment by rblakemesser** [comment] 2015-11-23 20:46
You can see the Slack's status page here: https://status.slack.com/

**Comment by jnankin** [comment] 2015-11-23 20:46
I actually cant even hit the status page...

**Comment by wikier** [comment] 2015-11-24 07:58
same here, so giving a try to the official client

**Comment by nadar** [comment] 2015-11-24 08:01
same here, switched to official client.

**Comment by raelgc** [comment] 2015-11-24 09:47
@wikier and @nadar Not sure if you understood the latest messages. ScudCloud was updated and it's working normally.

**Slack itself** was facing problems, including their status page.

Of course, you're free to use any client you want. And it's great the fact we have now 3 clients on Linux, so, in case of problems, we can switch between them.

**Comment by nadar** [comment] 2015-11-24 10:00
@raelgc i have read the latest messages and updated the application but it still displayed the loading screen.

Probably the application update did not work. i dunno. https://github.com/raelgc/scudcloud/issues/294#issuecomment-158153266

**Comment by raelgc** [comment] 2015-11-24 10:19
@nadar I cannot say for every supported distro. But it's updated for Ubuntu (all supported versions) and in code base. Maybe we need to wait for other maintainers.

As a workaround for now, you can apply the fix manually, editing the `/opt/scudcloud/lib/scudcloud.py` file and change the boolean values to be like this (usually line `81`):

``` python
        # Now with local storage we need history enabled
        QWebSettings.globalSettings().setAttribute(QWebSettings.PrivateBrowsingEnabled, False)
        # Enabling Local Storage (now required by Slack)
        QWebSettings.globalSettings().setAttribute(QWebSettings.LocalStorageEnabled, True)
```

Make sure `PrivateBrowsingEnabled` is `False` and `LocalStorageEnabled` is `True`. If `LocalStorageEnabled` line is not present, copy and paste it.

Slack changed their engine to now assume that all browsers and clients will answer for LocalStorage.

**Comment by anaisbetts** [comment] 2015-11-25 00:43
Hey all, lead developer of the Slack Linux client - the Scudcloud breakage on our end was definitely unintentional / accidental, we're never going to intentionally get in the way or try to cause problems for anyone who writes a 3rd party client, and we're _hugely_ appreciative of the hard work @raelgc and others have done to code up a great app for Linux users!

**Comment by boltronics** [comment] 2015-11-25 00:48
Thanks @paulcbetts. It's very reassuring to hear that from a Slack employee.

**Comment by raelgc** [comment] 2015-11-25 10:21
What a honor! @paulcbetts posting here!

Paul, thank you for the make that clear. It was clear to me that the issues discussed here were caused by Slack improving/upgrading their product and qtwebkit not being able to properly run these changes. 

But now we have this mention from you, it's clear to everyone!

**Closed as completed** 2015-11-27 23:41 UTC

**Comment by antonio-malcolm** [comment] 2016-01-15 23:03
This is still happening on v1.1.12, built from source.

**Comment by SuzanaK** [comment] 2017-03-10 12:43
I have the following version, installed from the package repository:

ScudCloud 1.39
Python 3.5.2
Qt 4.8.7
PyQt 4.11.4
SIP 4.17

...and still the same error. PrivateBrowsingEnabled is False and LocalStorageEnabled is set to True.

**Comment by raelgc** [comment] 2017-03-10 12:55
Hi @SuzanaK. Please, see discussion in #529. This is fixed, upgrade to the latest version (1.39 is not the latest).

**Comment by SuzanaK** [comment] 2017-03-10 13:04
Yes, I just upgraded to 1.43 and did a general package upgrade before, and now it works. Thank you!

**Comment by raelgc** [comment] 2017-03-10 13:09
You're welcome! :)

**Comment by ashishgupta13** [comment] 2017-03-14 16:10
Is there any issue with scudcloud again today as I started to face the same issue which was reported 4 days back. I am using LinuxMint 17.1
scudcloud --version

ScudCloud 1.43
Python 3.4.3
Qt 4.8.6
PyQt 4.10.4
SIP 4.15.5
