### ISSUE TITLE
code snippets CPU spikes

### ISSUE THREAD

**Issue by ThePeach** [raelgc/scudcloud#506] opened 2016-11-09 10:18 UTC
## ScudCloud Version

Paste the output for `scudcloud --version` below:
```ScudCloud 1.34
Python 3.5.2
Qt 4.8.7
PyQt 4.11.4
SIP 4.18.1
```

## Distro and Desktop info

  - Distribution: Archlinux
  - Version/Release: N/A (latest)
  - Desktop environment: Cinnamon

## Expected behavior

Interacting with the application should have no problems

## Actual behavior

the CPU is overloaded at every interaction

## Steps to reproduce
 1. paste a code snippet
 2. load the channel 
 3. scroll

**Comment by ThePeach** [comment] 2016-11-09 10:19
Just one more thing: collapsing the snippet will bring everything back to normal.

**Comment by raelgc** [comment] 2016-11-09 10:55
Hi @ThePeach and thanks for reporting this.

Unfortunately, this is a known behavior, duplicate of #140 (and reported at #253 too).

**Closed as completed by raelgc** 2016-11-09 10:55 UTC

**Comment by ThePeach** [comment] 2016-11-09 10:59
thanks @raelgc couldn't find it on my initial search. (weird morning nonetheless)

**Comment by raelgc** [comment] 2016-11-09 11:00
One possible workaround would be create a config to disable snippets expansion, and display them in the browser.

**Comment by raelgc** [comment] 2016-11-16 10:48
I just release a new version with an option to disable snippets (they'll be viewable in browser after click).

After upgrade, open your config file located at `~/.config/scudcloud/scudcloud.cfg` and add the following line:

```
Snippets=False
```
