### ISSUE TITLE
Possible to show existing ScudCloud process instead of launching another?

### ISSUE THREAD

**Issue by collinpeters** [raelgc/scudcloud#167] opened 2015-06-24 16:26 UTC
Currently if ScudCloud is running but closed (i.e. tray only) and I launch it again with my launcher (Kupfer), it tries to launch a second process with the error "The program is already running". Is it possible to open the existing ScudCloud process (i.e. just like clicking 'Show' in the tray) instead of the error?

**Comment by Larrik** [comment] 2015-06-26 18:00
I came here to post the same question

**Comment by raelgc** [comment] 2015-07-01 13:27
Thank you guys. But this is duplicate of #123

**Closed as completed by raelgc** 2015-07-01 13:27 UTC
