### ISSUE TITLE
Endless loading

### ISSUE THREAD

**Issue by vadim-su** [raelgc/scudcloud#411] opened 2016-03-08 15:20 UTC
![15](https://cloud.githubusercontent.com/assets/1702003/13605725/fd1df32a-e559-11e5-9cbf-071430115e45.png)

```
scudcloud --debug true
URL Changed: https://slack.com/signin
Link Clicked: https://golang-ru.slack.com/
URL Changed: https://golang-ru.slack.com/messages
```

```
scudcloud --debug true --version
ScudCloud 1.18
Python 3.4.3
Qt 4.8.7
PyQt 4.11.4
SIP 4.17
```

Distro name: gentoo

**Comment by raelgc** [comment] 2016-03-08 16:09
Duplicate of #335

**Closed as completed by raelgc** 2016-03-08 16:09 UTC
