### ISSUE TITLE
Spell checking doesn't work 

### ISSUE THREAD

**Issue by aaronorosen** [raelgc/scudcloud#226] opened 2015-09-17 06:09 UTC
Would be nice if the native spell checking that works in pidgin and chrome also worked in here.

**Comment by raelgc** [comment] 2015-09-17 13:09
Hi @aaronorosen, thanks for reporting this issue.

I agree, while it's not easy, as Python has not a direct binding for the SpellChecker plugin provided by webkit.

Anyway, this is a duplicate of #55

**Closed as completed by raelgc** 2015-09-17 13:09 UTC
