### ISSUE TITLE
Being able to go to or toggle the open Scudcloud window from the Unity Launcher.

### ISSUE THREAD

**Issue by cdysthe** [raelgc/scudcloud#256] opened 2015-10-13 10:21 UTC
I'm not sure if this is a bug or "feature" but if I click the Scudcloud launcher in the Unity launcher, and the application is open, I get an error message saying "the program is already open". I also get a second icon in the notification area. With other IM and chat clients I'm taken to the open window for the application and can then minimize and restore from the launcher. I have "minimize single window applications on click" set but that is not how the Scudcloud launcher currently works. If it had been possible to open a second Scudcloud session I would understand the current behavior, but it isn't so having it work like similar applications would be good.

**Comment by raelgc** [comment] 2015-10-13 10:41
Hi @cdysthe. Sounds like you've minimized to tray and clicking in the ScudCloud icon in Unity Launcher is trying to launch a new instance instead of display the current one. Am I correct?

**Comment by cdysthe** [comment] 2015-10-13 11:00
I guess that is a simpler way to describe it. All I want is that I am always taken to the open Scudcloud window when I click on the icon. I am using virtual desktops. Maybe that complicates it?

**Comment by raelgc** [comment] 2015-10-13 11:30
I think the virtual desktop is not the problem. The issue is happening when the ScudCloud icon is locked to the launcher. Some way, the launcher is not detecting the running application in systray and is trying to launch a new instance.

**Comment by raelgc** [comment] 2015-10-20 23:41
I realized this is duplicate of #66. Which, by the way, I fixed few minutes ago. But I"ll be able to publish the new version only in the next few days.

**Closed as completed by raelgc** 2015-10-20 23:41 UTC
