### ISSUE TITLE
scudcloud uses too much CPU

### ISSUE THREAD

**Issue by tigerand** [raelgc/scudcloud#152] opened 2015-06-17 19:49 UTC
when the scudcloud application window has the focus on my Desktop, it consumes massive amounts of CPU.  There's no good reason for that.  Sure, it may be animating various little things on occassion, but that _should_ be hardly noticeable CPU wise.  Some things I expect might bump up the CPU usage a bit, like hitting the arrow key to start editing a previous message, or when typing fast and it's hammering away at hunspell all the time.  But when completely idle, there should be no obviously noticeable CPU usage.

**top** lists the program as 'python'.  It mostly sits at ~100% for one core.

It also consumes massive amounts of CPU when doing the desktop notification for a push notification.

Ubuntu 14.04.  Unity.
8-logical core 2.4GHz base clock Intel E3 processor.

**Comment by raelgc** [comment] 2015-06-19 16:42
Hi @tigerand and thank you for reporting this issue.

In some channels or room, I heard from people this unusual behaviour. 

Unfortunately, ScudCloud has not that much control over this, as we're using a webkit container to render Slack. Maybe upgrade to webkit5, not sure.

Anyway, today I just added one option to start ScudCloud with all plugins disabled: `scudcloud --no_plugins=True`

Other option can be use Slack in Firefox + [Native notifications plugin](https://github.com/mkiol/GNotifier).

**Comment by raelgc** [comment] 2015-06-23 18:17
@tigerand Can you update and check if the CPU usage is a bit lower now?

**Comment by tigerand** [comment] 2015-06-26 00:16
_substantial_ improvement when idle.

still uses too much when it's up to something, especially desktop notifications and receiving a message from someone, but i'll take what i can get.

i noticed the web interface also now uses less CPU when idle, but the app is slightly more responsive because it's not running inside chrome browser.  or perhaps that's my imagination.  trying to get some extra lifetime out of my 10+ year old laptop!

thanks for the nice app.

-a

**Comment by tomchiverton** [comment] 2015-07-02 09:20
On Kubuntu 14.04, there's no CPU usage to speak off, focused or not. About 10% when I'm typing.

**Comment by tigerand** [comment] 2015-07-02 17:29
You are correct.  CPU usage is substantially improved -- one might say
completely cured -- in all areas, not just in idle or off-focus times.
I was wrong in my previous email where I said it still used too much CPU
during some operations.  It used to use so much CPU during desktop
notifications that it would hog out the X server and "freeze" the
whole desktop for 2-3 seconds.  Now, it's completely unnoticeable and
smooth during notifications.  Very nice.  I've switched over to the app
on all my computers.  You guys do some good work.

Thanks!

**Comment by ghost** [comment] 2015-09-24 21:31
I'm still seeing a lot of cpu usage (and noticieably slower performance) when snippets are open.

**Comment by raelgc** [comment] 2015-09-25 00:14
Snippets, files... probably we'll see a performance improvement while upgrading to Qt5, as discussed on #140. I'll mark this as duplicate of it.

**Closed as completed by raelgc** 2015-09-25 00:14 UTC

**Comment by raelgc** [comment] 2016-11-16 10:49
I just release a new version with an option to disable snippets (they'll be viewable in browser after click).

After upgrade, open your config file located at `~/.config/scudcloud/scudcloud.cfg` and add the following line:

```
Snippets=False
```
