### ISSUE TITLE
Feature request: _NET_WM_STATE should be set to urgent when a notification is sent

### ISSUE THREAD

**Issue by sagotsky** [raelgc/scudcloud#171] opened 2015-06-26 14:13 UTC
I keep missing messages because my window manager doesn't flash the window.  The notifications are great, but only if I'm paying attention.  If I go to the bathroom or grab a coffee, I don't see those notifications.  Could scudcloud please set its windows to urgent whenever a notification is sent?

**Comment by raelgc** [comment] 2015-09-10 18:04
Hi @sagotsky and really sorry for my late response.

Which desktop environment are you using?

**Comment by raelgc** [comment] 2015-09-10 18:15
In the past, ScudCloud was flashing its own window, but I removed in #22 due some DEs not properly handling `QApplication.alert` event.

So, I kept only Unity flash, which is ignored in other DEs.

**Comment by sagotsky** [comment] 2015-09-10 20:47
I'm on xmonad.  No worries about the late response.

I'd still like to see this feature, but it's not really urgent.  I wrote https://github.com/sagotsky/.dotfiles/blob/master/scripts/flag-urgent.sh and stuck it in my dunstrc for scudcloud events.  TBH, I'd probably continue doing this unless you went really overboard on the feature because I've grown accustomed to being able to only run 'flag-urgent.sh' when certain people or chats have activity.

**Comment by raelgc** [comment] 2015-09-10 21:55
I'll try restore the flash. To avoid duplication, I'll mark this as duplicate of #130

**Closed as completed by raelgc** 2015-09-10 21:55 UTC
